# Generated by Django 4.2.5 on 2023-09-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_enquiry_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='product_title',
            field=models.CharField(max_length=1000),
        ),
    ]
