# Generated by Django 4.2.5 on 2023-09-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_enquiry_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
