# Generated by Django 4.2.5 on 2023-09-26 11:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='location_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
