# Generated by Django 4.2.5 on 2023-09-27 05:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_companyinfo_delete_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('messageMD', ckeditor.fields.RichTextField()),
                ('mdName', models.CharField(max_length=200)),
                ('mdImage', models.ImageField(upload_to='mdImage/')),
                ('image', models.ImageField(upload_to='companyImg/')),
                ('title', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
