# Generated by Django 4.2.5 on 2023-09-27 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_aboutus_description_remove_aboutus_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
