# Generated by Django 4.2.5 on 2023-09-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_adsimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsimg',
            name='title',
        ),
    ]
