# Generated by Django 4.2.5 on 2023-09-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_adsimg_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdsImg',
            new_name='BannerImg',
        ),
        migrations.RenameField(
            model_name='bannerimg',
            old_name='ads_Img',
            new_name='banner_Img',
        ),
    ]
