# Generated by Django 4.2.5 on 2023-09-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_adsimg_bannerimg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='twitter_link',
            new_name='youtube_link',
        ),
    ]
