# Generated by Django 4.2.5 on 2023-09-29 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_twitter_link_companyinfo_youtube_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
