# Generated by Django 4.2.5 on 2023-09-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_enquiry_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='product_title',
        ),
    ]
