# Generated by Django 4.2.5 on 2023-09-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_contactus_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='location_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
