# Generated by Django 4.2.5 on 2023-09-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_companyinfo_location_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
    ]
