# Generated by Django 4.2.5 on 2023-09-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_slider_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='order_number',
        ),
    ]
