# Generated by Django 4.2.5 on 2023-10-01 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_enquiry_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='comment',
            new_name='message',
        ),
    ]
