# Generated by Django 4.2.5 on 2023-10-01 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_rename_comment_enquiry_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
