# Generated by Django 4.2.5 on 2023-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_companyinfo_youtube_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecatelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField()),
                ('eCatelog', models.TextField()),
            ],
        ),
    ]
