# Generated by Django 4.2.5 on 2023-10-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_ecatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecatelog',
            name='eCatelog',
            field=models.URLField(),
        ),
    ]
