# Generated by Django 4.2.5 on 2023-10-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_ecatelog_ecatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecatelog',
            name='eCatelog',
            field=models.URLField(max_length=10000),
        ),
    ]
