# Generated by Django 4.2.5 on 2023-10-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_ecatelog_ecatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecatelog',
            name='title',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
